/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/about': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns information about the instance */
    get: operations['getAbout']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns the info of the authenticated user */
    get: operations['getUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/page': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns the page information */
    get: operations['getPage']
    /** Attempts to save changes to a page */
    put: operations['putPage']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/page-contributors': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Returns the contributors of a page */
    get: operations['getPage-contributors']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/page-permission': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Checks whether the authenticated user is allowed to edit a page */
    get: operations['getPage-permission']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/pages': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Runs a query against the pages in database. Most recently updated pages are returned first. */
    get: operations['getPages']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getAbout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            name: string
          }
        }
      }
    }
  }
  getUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json':
            | {
                /** @constant */
                authenticated: true
                /** @description A user object */
                user: {
                  /** @description Numeric ID, represents the user from GitHub API */
                  id: number
                  /** @description Display name of the user */
                  name: string
                  /** @description Firebase UID */
                  uid: string
                }
              }
            | {
                /** @constant */
                authenticated: false
                reason: string
              }
        }
      }
    }
  }
  getPage: {
    parameters: {
      query: {
        pageRef: string
        withFile?: string
        revalidate?: string
        render?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @enum {number} */
            status: 200 | 301 | 404 | 500
            pageRef: string
            targetPageRef?: string
            title: string
            file?: {
              path: string
              content: string
              revision?: string
            }
            content: string
            rendered?: {
              html: string
              headings: {
                id: string
                label: string
                rank: number
              }[]
            }
            frontMatter: {
              [key: string]: unknown
            }
            lastModified?: string
            lastModifiedBy?: string[]
            perf: string[]
          }
        }
      }
    }
  }
  putPage: {
    parameters: {
      query: {
        pageRef: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          newContent: string
          oldRevision?: string
        }
        'application/x-www-form-urlencoded': {
          newContent: string
          oldRevision?: string
        }
        'multipart/form-data': {
          newContent: string
          oldRevision?: string
        }
      }
    }
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            revision?: string
          }
        }
      }
      /** @description Response for status 403 */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: string
          }
        }
      }
    }
  }
  'getPage-contributors': {
    parameters: {
      query: {
        pageRef: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            contributors: {
              login: string
              avatarUrl: string
              contributions: number
            }[]
            perf: string[]
          }
        }
      }
    }
  }
  'getPage-permission': {
    parameters: {
      query: {
        pageRef: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            granted: boolean
            reason?: string
          }
        }
      }
    }
  }
  getPages: {
    parameters: {
      query?: {
        q?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Response for status 200 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            count: number
            results: {
              lastModified: string | null
              pageRef: string
              frontMatter: {
                [key: string]: unknown
              }
            }[]
            explain?: unknown
          }
        }
      }
    }
  }
}
